/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {

    public static void main (String[] args){


    }

    public int []  roll (int n) {

        // declare array to get the values inside
        int [] rollArray = new int[n];
        int low = 1;
        int high = 6;
        Random rand = new Random();
        // create a random number
        for (int i = 0 ; i < n ; i++ ){

            rollArray[i] = rand.nextInt(high - low) + low;

        }
        return rollArray;
    }

    public boolean containsDuplicates (int [] testArray) {
        for (int i = 0 ; i < testArray.length ; i++){
            for(int j = 0 ; j < testArray.length ; j++) {
                if (i != j && testArray[i] == testArray[j]){ // check that the value is not at the same index
                    return true;
                }
            }
        }
        return false;
    }
    public float findingAverage(int [] array) {
        int sum = 0;
        float average;

        for (int i : array) {
            sum+= array[i];
        }
        average = sum / array.length;
        return average;
    }

    public int []  leastAverage  (int [][] arrayOfArrays){
        float avg = 1;
        float avg2;
        int sum = 0;
        int index = 1;
        for (int i = 0 ; i < arrayOfArrays.length ; i++){
            sum = 0;
            avg2 = avg; // each time assign the avg to another variable avg2 so when avg is updated it can be compared
            for(int j = 0 ; j < arrayOfArrays[i].length ; j++){
                sum = sum + arrayOfArrays[i][j];
            }
            avg = (float) sum / arrayOfArrays[i].length;
            if(avg < avg2){
                index = i; // we are requiring the index from the beginning to return its array
            }
        }
        return arrayOfArrays[index];
    }




    public boolean someLibraryMethod() {
        return true;
    }
}