/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {



    public boolean someLibraryMethod() {
        return true;
    }

    public Library(){

    }

    public static void main(String[] args) {
        Review review = new Review("nice", "bayan", 4);
        Shop shop = new Shop("M & Z", "cloths", "25$");
        System.out.println(shop.price);
    }

}
