/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String handlingWeatherData (int [][] arrayOfArrays){
        int min = arrayOfArrays[0][0];
        int max = arrayOfArrays[0][0];

        HashSet <Integer> temperature = new HashSet<Integer>();
        ArrayList<Integer> notFound = new ArrayList<Integer>();
        for (int [] array : arrayOfArrays){
            for (int num : array) {
                if (num > max) {
                    max = num;
                }
                if (num < min) {
                    min = num;
                }
                temperature.add(num);
            }
        }
        for (int i = min +1 ; i < max ; i++){
            if(!temperature.contains(i)){
                notFound.add(i);
            }
        }
        String returnedString = "High: " + max + "/nLow" + min;
        for(int iter: notFound){
            returnedString+= "/nNever saw temperature: " + iter;
        }
        return returnedString;
    }

//    public String tally(List<String> list){
//        int votes;
//        HashSet<String> names = new HashSet<String>(list);
//        HashMap<String, Integer> vote = new HashMap();
//        for(String name : list){
//            if(list.contains(name)){
//                votes++;
//            }
//        }
//    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
