/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void testRestaurantString(){
      Restaurant restaurant = new Restaurant("FireFly",5, "10$");
      String actual = restaurant.toString();
      String expected = "Restaurant{name='FireFly', rating=5, price='10$'}";
      assertEquals(expected,actual);
    }

    @Test void testReviewString(){
        Review review = new Review("Very expensive compared to the service!" , "Bayan" , 2);
        String actual = review.toString();
        String expected = "Review{body='Very expensive compared to the service!', author='Bayan', numberOfStars=2}";
        assertEquals(expected,actual);
    }

    @Test void testAddMethod(){
        Review review = new Review("Excellent service", "Nada", 4);
        Restaurant restaurant = new Restaurant("Alia", (float) 4.3, "50$");
        restaurant.addReview(review);
        assertEquals("Nada", review.getAuthor());
        System.out.println(restaurant.restaurantReviews.get(0));


    }
}
